name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: "./actions/action.sh" # запустить скрипт
      shell: sh # в интерпретаторе sh
